### ISSUE TITLE
Cant build 

### ISSUE THREAD

**Issue by e11iot-1337** [dhinakg/aeota#3]
```
?@MacBook-Pro-? aeota % sudo make
Password:
clang++ -framework Foundation -fmodules -fobjc-arc -L. -lAppleArchive -g aastuff.m -o aastuff
2024-06-12 17:07:17.416 xcodebuild[4913:131848] [MT] DVTSDK: Skipped SDK /Applications/Xcode.app/Contents/Developer/Platforms/iPhoneOS.platform/Developer/SDKs/iPhoneOS15.2.sdk; its version (9.3) is below required minimum (15.2) for the iphoneos platform.
aastuff.m:46:84: warning: incompatible pointer types sending 'bool *' to parameter of type 'BOOL * _Nullable' (aka 'signed char *') [-Wincompatible-pointer-types]
        if (![[NSFileManager defaultManager] fileExistsAtPath:out_path isDirectory:&is_directory]) {
                                                                                   ^~~~~~~~~~~~~
/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX.sdk/System/Library/Frameworks/Foundation.framework/Headers/NSFileManager.h:242:72: note: passing argument to parameter 'isDirectory' here
- (BOOL)fileExistsAtPath:(NSString *)path isDirectory:(nullable BOOL *)isDirectory;
                                                                       ^
1 warning generated.
Undefined symbols for architecture x86_64:
  "_AAAssetExtractorCreate", referenced from:
      _main in aastuff-d9de4d.o
  "_AAAssetExtractorDestroy", referenced from:
      _main in aastuff-d9de4d.o
  "_AAAssetExtractorWrite", referenced from:
      _main in aastuff-d9de4d.o
ld: symbol(s) not found for architecture x86_64
clang: error: linker command failed with exit code 1 (use -v to see invocation)
make: *** [aastuff] Error 1
?@MacBook-Pro-? aeota % sudo make -v
GNU Make 3.81
Copyright (C) 2006  Free Software Foundation, Inc.
This is free software; see the source for copying conditions.
There is NO warranty; not even for MERCHANTABILITY or FITNESS FOR A
PARTICULAR PURPOSE.

This program built for i386-apple-darwin11.3.0
```

**Comment by dhinakg** [comment]
What macOS and Xcode versions are you using?

**Comment by malhal** [comment]
Worked on macOS 14.6 with Xcode 16b4 & 15.4 installed
```
?@Mac? aeota % make
clang++ -fmodules -fobjc-arc -Iinclude -Wall -Werror -Wunreachable-code -Llib -framework Foundation -lAppleArchive src/aastuff.m src/args.m src/extract.m src/extract_standalone.m -o aastuff
codesign -f -s - aastuff
aastuff: replacing existing signature
clang++ -DAASTUFF_STANDALONE=1 -fmodules -fobjc-arc -Iinclude -Wall -Werror -Wunreachable-code -Llib -framework Foundation -lAppleArchive src/aastuff.m src/args.m src/extract.m src/extract_standalone.m -o aastuff_standalone
codesign -f -s - aastuff_standalone
aastuff_standalone: replacing existing signature
?@Mac? aeota % ls
Makefile		get_key.py		requirements.txt
README.md		include			src
aastuff			lib			test_extract.sh
aastuff_standalone	read_headers.py		test_get_key.sh
?@Mac? aeota % ./aastuff
Input archive is required
Usage: aastuff [options]
Options:
  -i, --input <archive>
      Input archive to extract
  -o, --output <directory>
      Output directory for extracted files
  -k, --key <base64>
      Key in base64 format for encrypted archives
  -h, --help
      Display this help message
  -v, --version
      Display the version number
?@Mac? aeota % ./aastuff_standalone 
Input archive is required
Usage: aastuff_standalone [options]
Options:
  -l, --list
      List the contents of the archive instead of extracting it
  -i, --input <archive>
      Input archive to extract
  -o, --output <directory>
      Output directory for extracted files
  -k, --key <base64>
      Key in base64 format for encrypted archives
  -h, --help
      Display this help message
  -v, --version
      Display the version number
  -f, --filter <pattern>
      Filter files by glob pattern
  -r, --regex <pattern>
      Filter files by regex pattern
```
Now need to try and setup the python virtual environment...
